### ISSUE TITLE
Stop/pause videos on slide change

### ISSUE THREAD

**Issue by Raimond82** [banthagroup/fslightbox#137]
When I change the video on a video slideshow, the current video continues playing, and if i play another video both sound at same time.

It's possible to stop the previous video on change?

**Comment by piotrzdziarski** [comment]
In basic version it's not possible to pause videos on slide change, but it's possible in the pro version thanks to onSlideChange event. It's described here: [https://github.com/banthagroup/fslightbox-react/issues/153](https://github.com/banthagroup/fslightbox-react/issues/153)
Only difference is getting source from sources array, as it's not React there is no **current** property:
```js
const source = sources[i];
```
instead of
```js
const source = sources[i].current;
```
